FROM python:3.6.7

ENV PROJECT_HOME /chatterbox
ENV PROJECT_EXE /chatterbox/main.py
ENV PROJECT_README /chatterbox/README.md

ENV PROJECT_REQUIREMENTS /chatterbox/requirements.txt
ENV PROJECT_SRC /chatterbox/src

RUN mkdir $PROJECT_HOME

COPY src $PROJECT_SRC
COPY main.py $PROJECT_EXE
COPY README.md $PROJECT_README
COPY requirements.txt $PROJECT_REQUIREMENTS

RUN pip install -r $PROJECT_REQUIREMENTS

RUN chmod 755 $PROJECT_EXE

CMD python $PROJECT_EXE